version: '2'
name: nginx
services:
  nginx:
    image: nginx:1.27.1-alpine
    container_name: nginx
    networks:
      - mynetwork
    volumes:
      - nginx-config:/etc/nginx
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
#      - 443:443
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  nginx-config:
  letsencrypt:

networks:
  mynetwork:
    external: true